### ISSUE TITLE
Make “ Google Maps “ Mobile Responsive 

### ISSUE THREAD

**Issue by YourMobileGeek** [FSUInnovationHub/InnovationHubWebsite#2]
The current view of Google Maps on the website is distorting the mobile layout completely. Just needs to be resized a bit where it could display as an image and then can link out to the actual Google Maps url. 

<img width="412" alt="screen shot 2018-02-23 at 5 01 42 pm" src="https://user-images.githubusercontent.com/8063614/36619020-4a3cbfb0-18bb-11e8-9ab6-e2a34648b963.png">

**Comment by cynamonster** [comment]
resolved

**Comment by YourMobileGeek** [comment]
Awesome, thanks Cynamon!
